--- #YAML:1.0
name:               Bio-PhyloTastic
version:            0.1
abstract:           ~
author:
    - Rutger Vos
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bio::Phylo:      0.50
    JSON:            0
    LWP::UserAgent:  0
    Scalar::Util:    0
    URI::Escape:     0
    XML::Twig:       0
    XML::XML2JSON:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
